version: '3'

services:
  db:
    image: postgres
    
    env_file: 
      - docker.env

    ports:
      - "5432:5432"
    volumes:
      - data-postgresql:/var/lib/postgresql
    networks:
      - postgres-network
      
  db_pgadmin:
    image: dpage/pgadmin4

    env_file: 
      - docker.env
     
    ports:
      - "15432:80"
    depends_on:
      - db
    networks:
      - postgres-network

volumes:
  data-postgresql:
    external: true

networks: 
  postgres-network:
    driver: bridge